// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iycuseacwchssxqhdpvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5Y3VzZWFjd2Noc3N4cWhkcHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzk4MzIsImV4cCI6MjA1OTg1NTgzMn0.tMHJvY4bI2pdiN6hHzvRRObKh09ytZUmlpE7vsfgZ6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);